### ISSUE TITLE
Facebook share button not correctly grab URL

### ISSUE THREAD

**Issue by wmswina** [ITPrism/ITPShare-Plugin#53]
My only problem is that the URL grab by the share button is incorrect.
you can find it here.
http://loytape.com.my/new/adhesive-tape/masking-tape-general-purpose-mkt-01-detail

i don't know what's the wrong here.. either the share button problem, or joomla it self..
thanks in advance

**Comment by todordev** [comment]
Thank you for your post!
Hmm...That is strange! Do you use VirtueMart? 
I am going to check and fix it.

**Comment by wmswina** [comment]
Yah, I'm using VirtueMart. but never mind, I've solved it.
My solution is I change line 894
`$uri = $article->link;`
to
`$uri = $this->getCurrentURI($url);`

I don't know this is a good approach or not, but at least it works.

**Comment by todordev** [comment]
Yeah. It could be good solution.
Thank you!
